/* Generated by re2c 0.13.5 on Tue Mar 15 16:03:58 2016 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "php_phalcon.h"

#include "mvc/model/query/scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 40 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  24,  24,  24,  24,  24,  24,  24, 
				 24,  26,  26,  24,  24,  26,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 26,  24,   8,  24,  24,  24,  24,  16, 
				 24,  24,  24,  24,  24,  56,  24,  24, 
				252, 252, 252, 252, 252, 252, 252, 252, 
				252, 252,  28,  24,  24,  24,  24,  24, 
				 24, 188, 188, 188, 188, 188, 188,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				 60,  60,  60,  24,   4,  24,  24,  60, 
				 24, 188, 188, 188, 188, 188, 188,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				188,  60,  60,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
			};

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy71;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy69;
			case '!':	goto yy52;
			case '"':	goto yy31;
			case '%':	goto yy44;
			case '&':	goto yy63;
			case '\'':	goto yy32;
			case '(':	goto yy48;
			case ')':	goto yy50;
			case '*':	goto yy40;
			case '+':	goto yy36;
			case ',':	goto yy46;
			case '-':	goto yy38;
			case '.':	goto yy11;
			case '/':	goto yy42;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy15;
			case '<':	goto yy54;
			case '=':	goto yy58;
			case '>':	goto yy56;
			case '?':	goto yy13;
			case '@':	goto yy60;
			case 'A':
			case 'a':	goto yy5;
			case 'B':
			case 'b':	goto yy6;
			case 'C':
			case 'c':	goto yy7;
			case 'D':
			case 'd':	goto yy8;
			case 'E':
			case 'e':	goto yy9;
			case 'F':
			case 'f':	goto yy2;
			case 'G':
			case 'g':	goto yy24;
			case 'H':
			case 'h':	goto yy25;
			case 'I':
			case 'i':	goto yy20;
			case 'J':
			case 'j':	goto yy28;
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'y':
			case 'z':	goto yy34;
			case 'L':
			case 'l':	goto yy26;
			case 'N':
			case 'n':	goto yy27;
			case 'O':
			case 'o':	goto yy23;
			case 'R':
			case 'r':	goto yy29;
			case 'S':
			case 's':	goto yy19;
			case 'T':
			case 't':	goto yy30;
			case 'U':
			case 'u':	goto yy17;
			case 'V':
			case 'v':	goto yy21;
			case 'W':
			case 'w':	goto yy22;
			case '[':	goto yy35;
			case '\\':	goto yy33;
			case '^':	goto yy67;
			case 'x':	goto yy10;
			case '|':	goto yy61;
			case '~':	goto yy65;
			default:	goto yy73;
			}
yy2:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'U') {
				if (yych <= 'O') {
					if (yych == 'A') goto yy321;
					if (yych <= 'N') goto yy239;
					goto yy322;
				} else {
					if (yych == 'R') goto yy323;
					if (yych <= 'T') goto yy239;
					goto yy324;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'a') goto yy321;
					if (yych <= 'n') goto yy239;
					goto yy322;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy239;
						goto yy323;
					} else {
						if (yych == 'u') goto yy324;
						goto yy239;
					}
				}
			}
yy3:
/* #line 49 "scanner.re" */
			{
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			if (token->len > 2 && !memcmp(token->value, "0x", 2)) {
				token->opcode = PHQL_T_HINTEGER;
			} else {
				int i, alpha = 0;
				for (i = 0; i < token->len; i++) {
					unsigned char ch = token->value[i];
					if (!((ch >= '0') && (ch <= '9'))) {
						alpha = 1;
						break;
		 			}
				}
				if (alpha) {
					token->opcode = PHQL_T_IDENTIFIER;
				} else {
					token->opcode = PHQL_T_INTEGER;
				}
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 227 "scanner.c" */
yy4:
			yych = *++YYCURSOR;
			if (yych <= '@') {
				if (yych <= '.') {
					if (yych <= '-') goto yy3;
					goto yy315;
				} else {
					if (yych <= '/') goto yy3;
					if (yych <= '9') goto yy317;
					goto yy3;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'F') goto yy319;
					if (yych <= '`') goto yy3;
					goto yy319;
				} else {
					if (yych == 'x') goto yy319;
					goto yy3;
				}
			}
yy5:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'L') {
					if (yych == 'G') goto yy298;
					if (yych <= 'K') goto yy239;
					goto yy299;
				} else {
					if (yych == 'N') goto yy300;
					if (yych <= 'R') goto yy239;
					goto yy301;
				}
			} else {
				if (yych <= 'l') {
					if (yych == 'g') goto yy298;
					if (yych <= 'k') goto yy239;
					goto yy299;
				} else {
					if (yych <= 'n') {
						if (yych <= 'm') goto yy239;
						goto yy300;
					} else {
						if (yych == 's') goto yy301;
						goto yy239;
					}
				}
			}
yy6:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy289;
				if (yych <= 'X') goto yy239;
				goto yy290;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy239;
					goto yy289;
				} else {
					if (yych == 'y') goto yy290;
					goto yy239;
				}
			}
yy7:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy271;
					goto yy239;
				} else {
					if (yych <= 'O') goto yy272;
					if (yych <= 'Q') goto yy239;
					goto yy273;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy271;
					goto yy239;
				} else {
					if (yych <= 'o') goto yy272;
					if (yych == 'r') goto yy273;
					goto yy239;
				}
			}
yy8:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy254;
				if (yych <= 'H') goto yy239;
				goto yy255;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy239;
					goto yy254;
				} else {
					if (yych == 'i') goto yy255;
					goto yy239;
				}
			}
yy9:
			yych = *++YYCURSOR;
			if (yych <= 'X') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy240;
					goto yy239;
				} else {
					if (yych <= 'N') goto yy241;
					if (yych <= 'W') goto yy239;
					goto yy242;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy240;
					goto yy239;
				} else {
					if (yych <= 'n') goto yy241;
					if (yych == 'x') goto yy243;
					goto yy239;
				}
			}
yy10:
			yych = *++YYCURSOR;
			goto yy239;
yy11:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy12;
			if (yych <= '9') goto yy235;
yy12:
/* #line 421 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 361 "scanner.c" */
yy13:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 64) {
				goto yy232;
			}
yy14:
/* #line 546 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 373 "scanner.c" */
yy15:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 32) {
				goto yy228;
			}
yy16:
/* #line 426 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 386 "scanner.c" */
yy17:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'S') {
				if (yych == 'P') goto yy217;
				if (yych <= 'R') goto yy100;
				goto yy218;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy100;
					goto yy217;
				} else {
					if (yych == 's') goto yy218;
					goto yy100;
				}
			}
yy18:
/* #line 369 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 421 "scanner.c" */
yy19:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy209;
			if (yych == 'e') goto yy209;
			goto yy100;
yy20:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy188;
					goto yy100;
				} else {
					if (yych <= 'N') goto yy189;
					if (yych <= 'R') goto yy100;
					goto yy191;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy188;
					goto yy100;
				} else {
					if (yych <= 'n') goto yy189;
					if (yych == 's') goto yy191;
					goto yy100;
				}
			}
yy21:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy182;
			if (yych == 'a') goto yy182;
			goto yy100;
yy22:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy175;
			if (yych == 'h') goto yy175;
			goto yy100;
yy23:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy156;
					if (yych <= 'M') goto yy100;
					goto yy157;
				} else {
					if (yych == 'R') goto yy159;
					if (yych <= 'T') goto yy100;
					goto yy161;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy156;
					if (yych <= 'm') goto yy100;
					goto yy157;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy100;
						goto yy159;
					} else {
						if (yych == 'u') goto yy161;
						goto yy100;
					}
				}
			}
yy24:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy151;
			if (yych == 'r') goto yy151;
			goto yy100;
yy25:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy145;
			if (yych == 'a') goto yy145;
			goto yy100;
yy26:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy133;
				if (yych <= 'H') goto yy100;
				goto yy134;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy100;
					goto yy133;
				} else {
					if (yych == 'i') goto yy134;
					goto yy100;
				}
			}
yy27:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy126;
				if (yych <= 'T') goto yy100;
				goto yy127;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy100;
					goto yy126;
				} else {
					if (yych == 'u') goto yy127;
					goto yy100;
				}
			}
yy28:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy122;
			if (yych == 'o') goto yy122;
			goto yy100;
yy29:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy117;
			if (yych == 'i') goto yy117;
			goto yy100;
yy30:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'H') goto yy109;
				if (yych <= 'Q') goto yy100;
				goto yy110;
			} else {
				if (yych <= 'h') {
					if (yych <= 'g') goto yy100;
					goto yy109;
				} else {
					if (yych == 'r') goto yy110;
					goto yy100;
				}
			}
yy31:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy14;
			goto yy107;
yy32:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy14;
			goto yy102;
yy33:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy14;
				if (yych <= 'Z') goto yy99;
				goto yy14;
			} else {
				if (yych == '`') goto yy14;
				if (yych <= 'z') goto yy99;
				goto yy14;
			}
yy34:
			yych = *++YYCURSOR;
			goto yy100;
yy35:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy14;
				if (yych == '[') goto yy14;
				goto yy94;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy14;
					goto yy94;
				} else {
					if (yych <= '`') goto yy14;
					if (yych <= 'z') goto yy94;
					goto yy14;
				}
			}
yy36:
			++YYCURSOR;
/* #line 396 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 598 "scanner.c" */
yy38:
			++YYCURSOR;
/* #line 401 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 606 "scanner.c" */
yy40:
			++YYCURSOR;
/* #line 406 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 614 "scanner.c" */
yy42:
			++YYCURSOR;
/* #line 411 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 622 "scanner.c" */
yy44:
			++YYCURSOR;
/* #line 416 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 630 "scanner.c" */
yy46:
			++YYCURSOR;
/* #line 431 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 638 "scanner.c" */
yy48:
			++YYCURSOR;
/* #line 436 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 646 "scanner.c" */
yy50:
			++YYCURSOR;
/* #line 441 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 654 "scanner.c" */
yy52:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '!') goto yy90;
			if (yych == '=') goto yy92;
/* #line 511 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 664 "scanner.c" */
yy54:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy55;
			if (yych <= '=') goto yy86;
			if (yych <= '>') goto yy88;
yy55:
/* #line 466 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 676 "scanner.c" */
yy56:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy84;
/* #line 471 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 685 "scanner.c" */
yy58:
			++YYCURSOR;
/* #line 476 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 693 "scanner.c" */
yy60:
			yych = *++YYCURSOR;
			if (yych == '>') goto yy80;
			if (yych == '@') goto yy82;
			goto yy14;
yy61:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '|') goto yy78;
/* #line 531 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 707 "scanner.c" */
yy63:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '&') goto yy76;
/* #line 526 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 716 "scanner.c" */
yy65:
			++YYCURSOR;
/* #line 516 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 724 "scanner.c" */
yy67:
			++YYCURSOR;
/* #line 521 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 732 "scanner.c" */
yy69:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy75;
yy70:
/* #line 536 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 743 "scanner.c" */
yy71:
			++YYCURSOR;
/* #line 541 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 751 "scanner.c" */
yy73:
			yych = *++YYCURSOR;
			goto yy14;
yy74:
			++YYCURSOR;
			yych = *YYCURSOR;
yy75:
			if (yybm[0+yych] & 2) {
				goto yy74;
			}
			goto yy70;
yy76:
			++YYCURSOR;
/* #line 491 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
/* #line 770 "scanner.c" */
yy78:
			++YYCURSOR;
/* #line 486 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
/* #line 778 "scanner.c" */
yy80:
			++YYCURSOR;
/* #line 501 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
/* #line 786 "scanner.c" */
yy82:
			++YYCURSOR;
/* #line 481 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
/* #line 794 "scanner.c" */
yy84:
			++YYCURSOR;
/* #line 461 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 802 "scanner.c" */
yy86:
			++YYCURSOR;
/* #line 456 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 810 "scanner.c" */
yy88:
			++YYCURSOR;
/* #line 451 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 818 "scanner.c" */
yy90:
			++YYCURSOR;
/* #line 496 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
/* #line 826 "scanner.c" */
yy92:
			++YYCURSOR;
/* #line 446 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 834 "scanner.c" */
yy94:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 4) {
				goto yy94;
			}
			if (yych == ']') goto yy97;
yy96:
			YYCURSOR = YYMARKER;
			if (yyaccept <= 0) {
				goto yy16;
			} else {
				goto yy14;
			}
yy97:
			++YYCURSOR;
/* #line 388 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 859 "scanner.c" */
yy99:
			++YYCURSOR;
			yych = *YYCURSOR;
yy100:
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '/') goto yy18;
					goto yy99;
				} else {
					if (yych <= '@') goto yy18;
					if (yych <= 'Z') goto yy99;
					goto yy18;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych <= '^') goto yy18;
					goto yy99;
				} else {
					if (yych <= '`') goto yy18;
					if (yych <= 'z') goto yy99;
					goto yy18;
				}
			}
yy101:
			++YYCURSOR;
			yych = *YYCURSOR;
yy102:
			if (yybm[0+yych] & 8) {
				goto yy101;
			}
			if (yych <= 0x00) goto yy96;
			if (yych <= '[') goto yy104;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy96;
			goto yy101;
yy104:
			++YYCURSOR;
/* #line 360 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 907 "scanner.c" */
yy106:
			++YYCURSOR;
			yych = *YYCURSOR;
yy107:
			if (yybm[0+yych] & 16) {
				goto yy106;
			}
			if (yych <= 0x00) goto yy96;
			if (yych <= '[') goto yy104;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy96;
			goto yy106;
yy109:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy114;
			if (yych == 'e') goto yy114;
			goto yy100;
yy110:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy111;
			if (yych != 'u') goto yy100;
yy111:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy112;
			if (yych != 'e') goto yy100;
yy112:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy113;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy113;
					if (yych <= 'z') goto yy99;
				}
			}
yy113:
/* #line 319 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 958 "scanner.c" */
yy114:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy115;
			if (yych != 'n') goto yy100;
yy115:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy116;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy116;
					if (yych <= 'z') goto yy99;
				}
			}
yy116:
/* #line 344 "scanner.re" */
			{
			token->opcode = PHQL_T_THEN;
			return 0;
		}
/* #line 987 "scanner.c" */
yy117:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy118;
			if (yych != 'g') goto yy100;
yy118:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy119;
			if (yych != 'h') goto yy100;
yy119:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy120;
			if (yych != 't') goto yy100;
yy120:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy121;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy121;
					if (yych <= 'z') goto yy99;
				}
			}
yy121:
/* #line 254 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 1024 "scanner.c" */
yy122:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy123;
			if (yych != 'i') goto yy100;
yy123:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy124;
			if (yych != 'n') goto yy100;
yy124:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy125;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy125;
					if (yych <= 'z') goto yy99;
				}
			}
yy125:
/* #line 239 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1057 "scanner.c" */
yy126:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy131;
			if (yych == 't') goto yy131;
			goto yy100;
yy127:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy128;
			if (yych != 'l') goto yy100;
yy128:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy129;
			if (yych != 'l') goto yy100;
yy129:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy130;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy130;
					if (yych <= 'z') goto yy99;
				}
			}
yy130:
/* #line 279 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1095 "scanner.c" */
yy131:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy132;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy132;
					if (yych <= 'z') goto yy99;
				}
			}
yy132:
/* #line 199 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1120 "scanner.c" */
yy133:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy142;
			if (yych == 'f') goto yy142;
			goto yy100;
yy134:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy136;
				if (yych <= 'L') goto yy100;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy100;
					goto yy136;
				} else {
					if (yych != 'm') goto yy100;
				}
			}
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy139;
			if (yych == 'i') goto yy139;
			goto yy100;
yy136:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy137;
			if (yych != 'e') goto yy100;
yy137:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy138;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy138;
					if (yych <= 'z') goto yy99;
				}
			}
yy138:
/* #line 214 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1171 "scanner.c" */
yy139:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy140;
			if (yych != 't') goto yy100;
yy140:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy141;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy141;
					if (yych <= 'z') goto yy99;
				}
			}
yy141:
/* #line 189 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 1200 "scanner.c" */
yy142:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy143;
			if (yych != 't') goto yy100;
yy143:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy144;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy144;
					if (yych <= 'z') goto yy99;
				}
			}
yy144:
/* #line 249 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1229 "scanner.c" */
yy145:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy146;
			if (yych != 'v') goto yy100;
yy146:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy147;
			if (yych != 'i') goto yy100;
yy147:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy148;
			if (yych != 'n') goto yy100;
yy148:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy149;
			if (yych != 'g') goto yy100;
yy149:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy150;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy150;
					if (yych <= 'z') goto yy99;
				}
			}
yy150:
/* #line 184 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 1270 "scanner.c" */
yy151:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy152;
			if (yych != 'o') goto yy100;
yy152:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy153;
			if (yych != 'u') goto yy100;
yy153:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy154;
			if (yych != 'p') goto yy100;
yy154:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy155;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy155;
					if (yych <= 'z') goto yy99;
				}
			}
yy155:
/* #line 179 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 1307 "scanner.c" */
yy156:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy170;
			if (yych == 'f') goto yy170;
			goto yy100;
yy157:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy158;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy158;
					if (yych <= 'z') goto yy99;
				}
			}
yy158:
/* #line 234 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1337 "scanner.c" */
yy159:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy160;
					if (yych <= ':') goto yy99;
				} else {
					if (yych == 'D') goto yy166;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy99;
					if (yych == '_') goto yy99;
				} else {
					if (yych == 'd') goto yy166;
					if (yych <= 'z') goto yy99;
				}
			}
yy160:
/* #line 209 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1363 "scanner.c" */
yy161:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy162;
			if (yych != 't') goto yy100;
yy162:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy163;
			if (yych != 'e') goto yy100;
yy163:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy164;
			if (yych != 'r') goto yy100;
yy164:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy165;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy165;
					if (yych <= 'z') goto yy99;
				}
			}
yy165:
/* #line 264 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 1400 "scanner.c" */
yy166:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy167;
			if (yych != 'e') goto yy100;
yy167:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy168;
			if (yych != 'r') goto yy100;
yy168:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy169;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy169;
					if (yych <= 'z') goto yy99;
				}
			}
yy169:
/* #line 159 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 1433 "scanner.c" */
yy170:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy171;
			if (yych != 's') goto yy100;
yy171:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy172;
			if (yych != 'e') goto yy100;
yy172:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy173;
			if (yych != 't') goto yy100;
yy173:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy174;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy174;
					if (yych <= 'z') goto yy99;
				}
			}
yy174:
/* #line 194 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 1470 "scanner.c" */
yy175:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy176;
			if (yych != 'e') goto yy100;
yy176:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'N') goto yy177;
				if (yych <= 'Q') goto yy100;
				goto yy179;
			} else {
				if (yych <= 'n') {
					if (yych <= 'm') goto yy100;
				} else {
					if (yych == 'r') goto yy179;
					goto yy100;
				}
			}
yy177:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy178;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy178;
					if (yych <= 'z') goto yy99;
				}
			}
yy178:
/* #line 339 "scanner.re" */
			{
			token->opcode = PHQL_T_WHEN;
			return 0;
		}
/* #line 1513 "scanner.c" */
yy179:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy180;
			if (yych != 'e') goto yy100;
yy180:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy181;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy181;
					if (yych <= 'z') goto yy99;
				}
			}
yy181:
/* #line 149 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 1542 "scanner.c" */
yy182:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy183;
			if (yych != 'l') goto yy100;
yy183:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy184;
			if (yych != 'u') goto yy100;
yy184:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy185;
			if (yych != 'e') goto yy100;
yy185:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy186;
			if (yych != 's') goto yy100;
yy186:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy187;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy187;
					if (yych <= 'z') goto yy99;
				}
			}
yy187:
/* #line 144 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 1583 "scanner.c" */
yy188:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy205;
			if (yych == 'i') goto yy205;
			goto yy100;
yy189:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'N') {
					if (yych <= ':') {
						if (yych >= '0') goto yy99;
					} else {
						if (yych <= '@') goto yy190;
						if (yych <= 'M') goto yy99;
						goto yy195;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'R') goto yy99;
						goto yy193;
					} else {
						if (yych <= 'T') goto yy194;
						if (yych <= 'Z') goto yy99;
					}
				}
			} else {
				if (yych <= 'm') {
					if (yych <= '^') {
						if (yych <= '\\') goto yy99;
					} else {
						if (yych != '`') goto yy99;
					}
				} else {
					if (yych <= 's') {
						if (yych <= 'n') goto yy195;
						if (yych <= 'r') goto yy99;
						goto yy193;
					} else {
						if (yych <= 't') goto yy194;
						if (yych <= 'z') goto yy99;
					}
				}
			}
yy190:
/* #line 229 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1633 "scanner.c" */
yy191:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy192;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy192;
					if (yych <= 'z') goto yy99;
				}
			}
yy192:
/* #line 274 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1658 "scanner.c" */
yy193:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy201;
			if (yych == 'e') goto yy201;
			goto yy100;
yy194:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy199;
			if (yych == 'o') goto yy199;
			goto yy100;
yy195:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy196;
			if (yych != 'e') goto yy100;
yy196:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy197;
			if (yych != 'r') goto yy100;
yy197:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy198;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy198;
					if (yych <= 'z') goto yy99;
				}
			}
yy198:
/* #line 244 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 1701 "scanner.c" */
yy199:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy200;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy200;
					if (yych <= 'z') goto yy99;
				}
			}
yy200:
/* #line 139 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 1726 "scanner.c" */
yy201:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy202;
			if (yych != 'r') goto yy100;
yy202:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy203;
			if (yych != 't') goto yy100;
yy203:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy204;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy204;
					if (yych <= 'z') goto yy99;
				}
			}
yy204:
/* #line 134 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 1759 "scanner.c" */
yy205:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy206;
			if (yych != 'k') goto yy100;
yy206:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy207;
			if (yych != 'e') goto yy100;
yy207:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy208;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy208;
					if (yych <= 'z') goto yy99;
				}
			}
yy208:
/* #line 219 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 1792 "scanner.c" */
yy209:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy212;
				if (yych <= 'S') goto yy100;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy100;
					goto yy212;
				} else {
					if (yych != 't') goto yy100;
				}
			}
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy211;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy211;
					if (yych <= 'z') goto yy99;
				}
			}
yy211:
/* #line 114 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 1829 "scanner.c" */
yy212:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy213;
			if (yych != 'e') goto yy100;
yy213:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy214;
			if (yych != 'c') goto yy100;
yy214:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy215;
			if (yych != 't') goto yy100;
yy215:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy216;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy216;
					if (yych <= 'z') goto yy99;
				}
			}
yy216:
/* #line 154 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 1866 "scanner.c" */
yy217:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy223;
			if (yych == 'd') goto yy223;
			goto yy100;
yy218:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy219;
			if (yych != 'i') goto yy100;
yy219:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy220;
			if (yych != 'n') goto yy100;
yy220:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy221;
			if (yych != 'g') goto yy100;
yy221:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy222;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy222;
					if (yych <= 'z') goto yy99;
				}
			}
yy222:
/* #line 309 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 1908 "scanner.c" */
yy223:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy224;
			if (yych != 'a') goto yy100;
yy224:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy225;
			if (yych != 't') goto yy100;
yy225:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy226;
			if (yych != 'e') goto yy100;
yy226:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy227;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy227;
					if (yych <= 'z') goto yy99;
				}
			}
yy227:
/* #line 109 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 1945 "scanner.c" */
yy228:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 32) {
				goto yy228;
			}
			if (yych != ':') goto yy96;
			++YYCURSOR;
/* #line 101 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1962 "scanner.c" */
yy232:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy232;
			}
/* #line 92 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 1977 "scanner.c" */
yy235:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy237;
			if (yych <= '9') goto yy235;
yy237:
/* #line 83 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 1992 "scanner.c" */
yy238:
			++YYCURSOR;
			yych = *YYCURSOR;
yy239:
			if (yybm[0+yych] & 128) {
				goto yy238;
			}
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '9') goto yy3;
					goto yy99;
				} else {
					if (yych <= 'F') goto yy3;
					if (yych <= 'Z') goto yy99;
					goto yy3;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych <= '^') goto yy3;
					goto yy99;
				} else {
					if (yych <= '`') goto yy3;
					if (yych <= 'z') goto yy99;
					goto yy3;
				}
			}
yy240:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy251;
			if (yych == 's') goto yy251;
			goto yy100;
yy241:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy249;
			if (yych == 'd') goto yy249;
			goto yy100;
yy242:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy244;
			if (yych == 'i') goto yy244;
			goto yy100;
yy243:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy244;
			if (yych != 'i') goto yy239;
yy244:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy245;
			if (yych != 's') goto yy100;
yy245:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy246;
			if (yych != 't') goto yy100;
yy246:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy247;
			if (yych != 's') goto yy100;
yy247:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy248;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy248;
					if (yych <= 'z') goto yy99;
				}
			}
yy248:
/* #line 314 "scanner.re" */
			{
			token->opcode = PHQL_T_EXISTS;
			return 0;
		}
/* #line 2075 "scanner.c" */
yy249:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy250;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy250;
					if (yych <= 'z') goto yy99;
				}
			}
yy250:
/* #line 354 "scanner.re" */
			{
			token->opcode = PHQL_T_END;
			return 0;
		}
/* #line 2100 "scanner.c" */
yy251:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy252;
			if (yych != 'e') goto yy100;
yy252:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy253;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy253;
					if (yych <= 'z') goto yy99;
				}
			}
yy253:
/* #line 349 "scanner.re" */
			{
			token->opcode = PHQL_T_ELSE;
			return 0;
		}
/* #line 2129 "scanner.c" */
yy254:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy263;
				if (yych <= 'R') goto yy239;
				goto yy264;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy239;
					goto yy263;
				} else {
					if (yych == 's') goto yy264;
					goto yy239;
				}
			}
yy255:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy256;
			if (yych != 's') goto yy100;
yy256:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy257;
			if (yych != 't') goto yy100;
yy257:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy258;
			if (yych != 'i') goto yy100;
yy258:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy259;
			if (yych != 'n') goto yy100;
yy259:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy260;
			if (yych != 'c') goto yy100;
yy260:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy261;
			if (yych != 't') goto yy100;
yy261:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy262;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy262;
					if (yych <= 'z') goto yy99;
				}
			}
yy262:
/* #line 284 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2193 "scanner.c" */
yy263:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy267;
			if (yych == 'e') goto yy267;
			goto yy100;
yy264:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy265;
			if (yych != 'c') goto yy100;
yy265:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy266;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy266;
					if (yych <= 'z') goto yy99;
				}
			}
yy266:
/* #line 174 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 2227 "scanner.c" */
yy267:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy268;
			if (yych != 't') goto yy100;
yy268:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy269;
			if (yych != 'e') goto yy100;
yy269:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy270;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy270;
					if (yych <= 'z') goto yy99;
				}
			}
yy270:
/* #line 119 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2260 "scanner.c" */
yy271:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy284;
			if (yych == 's') goto yy284;
			goto yy239;
yy272:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy278;
			if (yych == 'n') goto yy278;
			goto yy100;
yy273:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy274;
			if (yych != 'o') goto yy100;
yy274:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy275;
			if (yych != 's') goto yy100;
yy275:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy276;
			if (yych != 's') goto yy100;
yy276:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy277;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy277;
					if (yych <= 'z') goto yy99;
				}
			}
yy277:
/* #line 259 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 2307 "scanner.c" */
yy278:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy279;
			if (yych != 'v') goto yy100;
yy279:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy280;
			if (yych != 'e') goto yy100;
yy280:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy281;
			if (yych != 'r') goto yy100;
yy281:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy282;
			if (yych != 't') goto yy100;
yy282:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy283;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy283;
					if (yych <= 'z') goto yy99;
				}
			}
yy283:
/* #line 304 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 2348 "scanner.c" */
yy284:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'E') goto yy285;
				if (yych <= 'S') goto yy100;
				goto yy287;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy100;
				} else {
					if (yych == 't') goto yy287;
					goto yy100;
				}
			}
yy285:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy286;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy286;
					if (yych <= 'z') goto yy99;
				}
			}
yy286:
/* #line 334 "scanner.re" */
			{
			token->opcode = PHQL_T_CASE;
			return 0;
		}
/* #line 2387 "scanner.c" */
yy287:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy288;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy288;
					if (yych <= 'z') goto yy99;
				}
			}
yy288:
/* #line 299 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 2412 "scanner.c" */
yy289:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy292;
			if (yych == 't') goto yy292;
			goto yy239;
yy290:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy291;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy291;
					if (yych <= 'z') goto yy99;
				}
			}
yy291:
/* #line 164 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 2442 "scanner.c" */
yy292:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy293;
			if (yych != 'w') goto yy100;
yy293:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy294;
			if (yych != 'e') goto yy100;
yy294:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy295;
			if (yych != 'e') goto yy100;
yy295:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy296;
			if (yych != 'n') goto yy100;
yy296:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy297;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy297;
					if (yych <= 'z') goto yy99;
				}
			}
yy297:
/* #line 294 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 2483 "scanner.c" */
yy298:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy309;
			if (yych == 'a') goto yy309;
			goto yy100;
yy299:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy307;
			if (yych == 'l') goto yy307;
			goto yy100;
yy300:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy305;
			if (yych == 'd') goto yy305;
			goto yy100;
yy301:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy302;
					if (yych <= ':') goto yy99;
				} else {
					if (yych == 'C') goto yy303;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy99;
					if (yych == '_') goto yy99;
				} else {
					if (yych == 'c') goto yy303;
					if (yych <= 'z') goto yy99;
				}
			}
yy302:
/* #line 129 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 2524 "scanner.c" */
yy303:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy304;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy304;
					if (yych <= 'z') goto yy99;
				}
			}
yy304:
/* #line 169 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 2549 "scanner.c" */
yy305:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy306;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy306;
					if (yych <= 'z') goto yy99;
				}
			}
yy306:
/* #line 204 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 2574 "scanner.c" */
yy307:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy308;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy308;
					if (yych <= 'z') goto yy99;
				}
			}
yy308:
/* #line 289 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 2599 "scanner.c" */
yy309:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy310;
			if (yych != 'i') goto yy100;
yy310:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy311;
			if (yych != 'n') goto yy100;
yy311:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy312;
			if (yych != 's') goto yy100;
yy312:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy313;
			if (yych != 't') goto yy100;
yy313:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy314;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy314;
					if (yych <= 'z') goto yy99;
				}
			}
yy314:
/* #line 224 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 2640 "scanner.c" */
yy315:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy237;
			if (yych <= '9') goto yy315;
			goto yy237;
yy317:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '@') {
				if (yych <= '.') {
					if (yych <= '-') goto yy3;
					goto yy315;
				} else {
					if (yych <= '/') goto yy3;
					if (yych <= '9') goto yy317;
					goto yy3;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'F') goto yy319;
					if (yych <= '`') goto yy3;
				} else {
					if (yych != 'x') goto yy3;
				}
			}
yy319:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'F') {
				if (yych <= '/') goto yy3;
				if (yych <= '9') goto yy319;
				if (yych <= '@') goto yy3;
				goto yy319;
			} else {
				if (yych <= 'f') {
					if (yych <= '`') goto yy3;
					goto yy319;
				} else {
					if (yych == 'x') goto yy319;
					goto yy3;
				}
			}
yy321:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy341;
			if (yych == 'l') goto yy341;
			goto yy239;
yy322:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy331;
			if (yych == 'r') goto yy331;
			goto yy100;
yy323:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy328;
			if (yych == 'o') goto yy328;
			goto yy100;
yy324:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy325;
			if (yych != 'l') goto yy100;
yy325:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy326;
			if (yych != 'l') goto yy100;
yy326:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy327;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy327;
					if (yych <= 'z') goto yy99;
				}
			}
yy327:
/* #line 269 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 2731 "scanner.c" */
yy328:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy329;
			if (yych != 'm') goto yy100;
yy329:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy330;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy330;
					if (yych <= 'z') goto yy99;
				}
			}
yy330:
/* #line 124 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 2760 "scanner.c" */
yy331:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy332;
					if (yych <= ':') goto yy99;
				} else {
					if (yych == 'C') goto yy333;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy99;
					if (yych == '_') goto yy99;
				} else {
					if (yych == 'c') goto yy333;
					if (yych <= 'z') goto yy99;
				}
			}
yy332:
/* #line 329 "scanner.re" */
			{
			token->opcode = PHQL_T_FOR;
			return 0;
		}
/* #line 2786 "scanner.c" */
yy333:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy334;
			if (yych != 'e') goto yy100;
yy334:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy335;
			if (yych != 'i') goto yy100;
yy335:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy336;
			if (yych != 'n') goto yy100;
yy336:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy337;
			if (yych != 'd') goto yy100;
yy337:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy338;
			if (yych != 'e') goto yy100;
yy338:
			yych = *++YYCURSOR;
			if (yych == 'X') goto yy339;
			if (yych != 'x') goto yy100;
yy339:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy340;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy340;
					if (yych <= 'z') goto yy99;
				}
			}
yy340:
/* #line 40 "scanner.re" */
			{
			token->opcode = PHQL_T_FORCEINDEX;
			token->value = estrndup("FORCE INDEX", YYCURSOR - q + 1);
			token->len = YYCURSOR - q + 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 2838 "scanner.c" */
yy341:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy342;
			if (yych != 's') goto yy100;
yy342:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy343;
			if (yych != 'e') goto yy100;
yy343:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy99;
				} else {
					if (yych <= '@') goto yy344;
					if (yych <= 'Z') goto yy99;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy99;
					if (yych >= '_') goto yy99;
				} else {
					if (yych <= '`') goto yy344;
					if (yych <= 'z') goto yy99;
				}
			}
yy344:
/* #line 324 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 2871 "scanner.c" */
		}
/* #line 551 "scanner.re" */

	}

	return status;
}
