/* Generated by re2c 0.13.5 on Tue Mar 15 08:41:59 2016 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "php_phalcon.h"

#include "mvc/model/query/scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 40 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  24,  24,  24,  24,  24,  24,  24, 
				 24,  26,  26,  24,  24,  26,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 26,  24,   8,  24,  24,  24,  24,  16, 
				 24,  24,  24,  24,  24,  56,  24,  24, 
				252, 252, 252, 252, 252, 252, 252, 252, 
				252, 252,  28,  24,  24,  24,  24,  24, 
				 24, 188, 188, 188, 188, 188, 188,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				 60,  60,  60,  24,   4,  24,  24,  60, 
				 24, 188, 188, 188, 188, 188, 188,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				 60,  60,  60,  60,  60,  60,  60,  60, 
				188,  60,  60,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
				 24,  24,  24,  24,  24,  24,  24,  24, 
			};

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy72;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy70;
			case '!':	goto yy53;
			case '"':	goto yy32;
			case '%':	goto yy45;
			case '&':	goto yy64;
			case '\'':	goto yy33;
			case '(':	goto yy49;
			case ')':	goto yy51;
			case '*':	goto yy41;
			case '+':	goto yy37;
			case ',':	goto yy47;
			case '-':	goto yy39;
			case '.':	goto yy12;
			case '/':	goto yy43;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy16;
			case '<':	goto yy55;
			case '=':	goto yy59;
			case '>':	goto yy57;
			case '?':	goto yy14;
			case '@':	goto yy61;
			case 'A':
			case 'a':	goto yy5;
			case 'B':
			case 'b':	goto yy6;
			case 'C':
			case 'c':	goto yy7;
			case 'D':
			case 'd':	goto yy8;
			case 'E':
			case 'e':	goto yy9;
			case 'F':	goto yy2;
			case 'G':
			case 'g':	goto yy25;
			case 'H':
			case 'h':	goto yy26;
			case 'I':
			case 'i':	goto yy21;
			case 'J':
			case 'j':	goto yy29;
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'y':
			case 'z':	goto yy35;
			case 'L':
			case 'l':	goto yy27;
			case 'N':
			case 'n':	goto yy28;
			case 'O':
			case 'o':	goto yy24;
			case 'R':
			case 'r':	goto yy30;
			case 'S':
			case 's':	goto yy20;
			case 'T':
			case 't':	goto yy31;
			case 'U':
			case 'u':	goto yy18;
			case 'V':
			case 'v':	goto yy22;
			case 'W':
			case 'w':	goto yy23;
			case '[':	goto yy36;
			case '\\':	goto yy34;
			case '^':	goto yy68;
			case 'f':	goto yy10;
			case 'x':	goto yy11;
			case '|':	goto yy62;
			case '~':	goto yy66;
			default:	goto yy74;
			}
yy2:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'U') {
				if (yych <= 'O') {
					if (yych == 'A') goto yy241;
					if (yych <= 'N') goto yy240;
					goto yy338;
				} else {
					if (yych == 'R') goto yy243;
					if (yych <= 'T') goto yy240;
					goto yy244;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'a') goto yy241;
					if (yych <= 'n') goto yy240;
					goto yy242;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy240;
						goto yy243;
					} else {
						if (yych == 'u') goto yy244;
						goto yy240;
					}
				}
			}
yy3:
/* #line 50 "scanner.re" */
			{
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			if (token->len > 2 && !memcmp(token->value, "0x", 2)) {
				token->opcode = PHQL_T_HINTEGER;
			} else {
				int i, alpha = 0;
				for (i = 0; i < token->len; i++) {
					unsigned char ch = token->value[i];
					if (!((ch >= '0') && (ch <= '9'))) {
						alpha = 1;
						break;
		 			}
				}
				if (alpha) {
					token->opcode = PHQL_T_IDENTIFIER;
				} else {
					token->opcode = PHQL_T_INTEGER;
				}
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 227 "scanner.c" */
yy4:
			yych = *++YYCURSOR;
			if (yych <= '@') {
				if (yych <= '.') {
					if (yych <= '-') goto yy3;
					goto yy332;
				} else {
					if (yych <= '/') goto yy3;
					if (yych <= '9') goto yy334;
					goto yy3;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'F') goto yy336;
					if (yych <= '`') goto yy3;
					goto yy336;
				} else {
					if (yych == 'x') goto yy336;
					goto yy3;
				}
			}
yy5:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'L') {
					if (yych == 'G') goto yy315;
					if (yych <= 'K') goto yy240;
					goto yy316;
				} else {
					if (yych == 'N') goto yy317;
					if (yych <= 'R') goto yy240;
					goto yy318;
				}
			} else {
				if (yych <= 'l') {
					if (yych == 'g') goto yy315;
					if (yych <= 'k') goto yy240;
					goto yy316;
				} else {
					if (yych <= 'n') {
						if (yych <= 'm') goto yy240;
						goto yy317;
					} else {
						if (yych == 's') goto yy318;
						goto yy240;
					}
				}
			}
yy6:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy306;
				if (yych <= 'X') goto yy240;
				goto yy307;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy240;
					goto yy306;
				} else {
					if (yych == 'y') goto yy307;
					goto yy240;
				}
			}
yy7:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy288;
					goto yy240;
				} else {
					if (yych <= 'O') goto yy289;
					if (yych <= 'Q') goto yy240;
					goto yy290;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy288;
					goto yy240;
				} else {
					if (yych <= 'o') goto yy289;
					if (yych == 'r') goto yy290;
					goto yy240;
				}
			}
yy8:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy271;
				if (yych <= 'H') goto yy240;
				goto yy272;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy240;
					goto yy271;
				} else {
					if (yych == 'i') goto yy272;
					goto yy240;
				}
			}
yy9:
			yych = *++YYCURSOR;
			if (yych <= 'X') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy257;
					goto yy240;
				} else {
					if (yych <= 'N') goto yy258;
					if (yych <= 'W') goto yy240;
					goto yy259;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy257;
					goto yy240;
				} else {
					if (yych <= 'n') goto yy258;
					if (yych == 'x') goto yy260;
					goto yy240;
				}
			}
yy10:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'O') {
					if (yych == 'A') goto yy241;
					if (yych <= 'N') goto yy240;
					goto yy242;
				} else {
					if (yych == 'R') goto yy243;
					if (yych <= 'T') goto yy240;
					goto yy244;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'a') goto yy241;
					if (yych <= 'n') goto yy240;
					goto yy242;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy240;
						goto yy243;
					} else {
						if (yych == 'u') goto yy244;
						goto yy240;
					}
				}
			}
yy11:
			yych = *++YYCURSOR;
			goto yy240;
yy12:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy13;
			if (yych <= '9') goto yy236;
yy13:
/* #line 422 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 388 "scanner.c" */
yy14:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 64) {
				goto yy233;
			}
yy15:
/* #line 547 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 400 "scanner.c" */
yy16:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 32) {
				goto yy229;
			}
yy17:
/* #line 427 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 413 "scanner.c" */
yy18:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'S') {
				if (yych == 'P') goto yy218;
				if (yych <= 'R') goto yy101;
				goto yy219;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy101;
					goto yy218;
				} else {
					if (yych == 's') goto yy219;
					goto yy101;
				}
			}
yy19:
/* #line 370 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 448 "scanner.c" */
yy20:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy210;
			if (yych == 'e') goto yy210;
			goto yy101;
yy21:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy189;
					goto yy101;
				} else {
					if (yych <= 'N') goto yy190;
					if (yych <= 'R') goto yy101;
					goto yy192;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy189;
					goto yy101;
				} else {
					if (yych <= 'n') goto yy190;
					if (yych == 's') goto yy192;
					goto yy101;
				}
			}
yy22:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy183;
			if (yych == 'a') goto yy183;
			goto yy101;
yy23:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy176;
			if (yych == 'h') goto yy176;
			goto yy101;
yy24:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy157;
					if (yych <= 'M') goto yy101;
					goto yy158;
				} else {
					if (yych == 'R') goto yy160;
					if (yych <= 'T') goto yy101;
					goto yy162;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy157;
					if (yych <= 'm') goto yy101;
					goto yy158;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy101;
						goto yy160;
					} else {
						if (yych == 'u') goto yy162;
						goto yy101;
					}
				}
			}
yy25:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy152;
			if (yych == 'r') goto yy152;
			goto yy101;
yy26:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy146;
			if (yych == 'a') goto yy146;
			goto yy101;
yy27:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy134;
				if (yych <= 'H') goto yy101;
				goto yy135;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy101;
					goto yy134;
				} else {
					if (yych == 'i') goto yy135;
					goto yy101;
				}
			}
yy28:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy127;
				if (yych <= 'T') goto yy101;
				goto yy128;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy101;
					goto yy127;
				} else {
					if (yych == 'u') goto yy128;
					goto yy101;
				}
			}
yy29:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy123;
			if (yych == 'o') goto yy123;
			goto yy101;
yy30:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy118;
			if (yych == 'i') goto yy118;
			goto yy101;
yy31:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'H') goto yy110;
				if (yych <= 'Q') goto yy101;
				goto yy111;
			} else {
				if (yych <= 'h') {
					if (yych <= 'g') goto yy101;
					goto yy110;
				} else {
					if (yych == 'r') goto yy111;
					goto yy101;
				}
			}
yy32:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy15;
			goto yy108;
yy33:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy15;
			goto yy103;
yy34:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy15;
				if (yych <= 'Z') goto yy100;
				goto yy15;
			} else {
				if (yych == '`') goto yy15;
				if (yych <= 'z') goto yy100;
				goto yy15;
			}
yy35:
			yych = *++YYCURSOR;
			goto yy101;
yy36:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy15;
				if (yych == '[') goto yy15;
				goto yy95;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy15;
					goto yy95;
				} else {
					if (yych <= '`') goto yy15;
					if (yych <= 'z') goto yy95;
					goto yy15;
				}
			}
yy37:
			++YYCURSOR;
/* #line 397 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 625 "scanner.c" */
yy39:
			++YYCURSOR;
/* #line 402 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 633 "scanner.c" */
yy41:
			++YYCURSOR;
/* #line 407 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 641 "scanner.c" */
yy43:
			++YYCURSOR;
/* #line 412 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 649 "scanner.c" */
yy45:
			++YYCURSOR;
/* #line 417 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 657 "scanner.c" */
yy47:
			++YYCURSOR;
/* #line 432 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 665 "scanner.c" */
yy49:
			++YYCURSOR;
/* #line 437 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 673 "scanner.c" */
yy51:
			++YYCURSOR;
/* #line 442 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 681 "scanner.c" */
yy53:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '!') goto yy91;
			if (yych == '=') goto yy93;
/* #line 512 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 691 "scanner.c" */
yy55:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy56;
			if (yych <= '=') goto yy87;
			if (yych <= '>') goto yy89;
yy56:
/* #line 467 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 703 "scanner.c" */
yy57:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy85;
/* #line 472 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 712 "scanner.c" */
yy59:
			++YYCURSOR;
/* #line 477 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 720 "scanner.c" */
yy61:
			yych = *++YYCURSOR;
			if (yych == '>') goto yy81;
			if (yych == '@') goto yy83;
			goto yy15;
yy62:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '|') goto yy79;
/* #line 532 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 734 "scanner.c" */
yy64:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '&') goto yy77;
/* #line 527 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 743 "scanner.c" */
yy66:
			++YYCURSOR;
/* #line 517 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 751 "scanner.c" */
yy68:
			++YYCURSOR;
/* #line 522 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 759 "scanner.c" */
yy70:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy76;
yy71:
/* #line 537 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 770 "scanner.c" */
yy72:
			++YYCURSOR;
/* #line 542 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 778 "scanner.c" */
yy74:
			yych = *++YYCURSOR;
			goto yy15;
yy75:
			++YYCURSOR;
			yych = *YYCURSOR;
yy76:
			if (yybm[0+yych] & 2) {
				goto yy75;
			}
			goto yy71;
yy77:
			++YYCURSOR;
/* #line 492 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
/* #line 797 "scanner.c" */
yy79:
			++YYCURSOR;
/* #line 487 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
/* #line 805 "scanner.c" */
yy81:
			++YYCURSOR;
/* #line 502 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
/* #line 813 "scanner.c" */
yy83:
			++YYCURSOR;
/* #line 482 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
/* #line 821 "scanner.c" */
yy85:
			++YYCURSOR;
/* #line 462 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 829 "scanner.c" */
yy87:
			++YYCURSOR;
/* #line 457 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 837 "scanner.c" */
yy89:
			++YYCURSOR;
/* #line 452 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 845 "scanner.c" */
yy91:
			++YYCURSOR;
/* #line 497 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
/* #line 853 "scanner.c" */
yy93:
			++YYCURSOR;
/* #line 447 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 861 "scanner.c" */
yy95:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 4) {
				goto yy95;
			}
			if (yych == ']') goto yy98;
yy97:
			YYCURSOR = YYMARKER;
			if (yyaccept <= 0) {
				goto yy17;
			} else {
				goto yy15;
			}
yy98:
			++YYCURSOR;
/* #line 389 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 886 "scanner.c" */
yy100:
			++YYCURSOR;
			yych = *YYCURSOR;
yy101:
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '/') goto yy19;
					goto yy100;
				} else {
					if (yych <= '@') goto yy19;
					if (yych <= 'Z') goto yy100;
					goto yy19;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych <= '^') goto yy19;
					goto yy100;
				} else {
					if (yych <= '`') goto yy19;
					if (yych <= 'z') goto yy100;
					goto yy19;
				}
			}
yy102:
			++YYCURSOR;
			yych = *YYCURSOR;
yy103:
			if (yybm[0+yych] & 8) {
				goto yy102;
			}
			if (yych <= 0x00) goto yy97;
			if (yych <= '[') goto yy105;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy97;
			goto yy102;
yy105:
			++YYCURSOR;
/* #line 361 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 934 "scanner.c" */
yy107:
			++YYCURSOR;
			yych = *YYCURSOR;
yy108:
			if (yybm[0+yych] & 16) {
				goto yy107;
			}
			if (yych <= 0x00) goto yy97;
			if (yych <= '[') goto yy105;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy97;
			goto yy107;
yy110:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy115;
			if (yych == 'e') goto yy115;
			goto yy101;
yy111:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy112;
			if (yych != 'u') goto yy101;
yy112:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy113;
			if (yych != 'e') goto yy101;
yy113:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy114;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy114;
					if (yych <= 'z') goto yy100;
				}
			}
yy114:
/* #line 320 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 985 "scanner.c" */
yy115:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy116;
			if (yych != 'n') goto yy101;
yy116:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy117;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy117;
					if (yych <= 'z') goto yy100;
				}
			}
yy117:
/* #line 345 "scanner.re" */
			{
			token->opcode = PHQL_T_THEN;
			return 0;
		}
/* #line 1014 "scanner.c" */
yy118:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy119;
			if (yych != 'g') goto yy101;
yy119:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy120;
			if (yych != 'h') goto yy101;
yy120:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy121;
			if (yych != 't') goto yy101;
yy121:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy122;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy122;
					if (yych <= 'z') goto yy100;
				}
			}
yy122:
/* #line 255 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 1051 "scanner.c" */
yy123:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy124;
			if (yych != 'i') goto yy101;
yy124:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy125;
			if (yych != 'n') goto yy101;
yy125:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy126;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy126;
					if (yych <= 'z') goto yy100;
				}
			}
yy126:
/* #line 240 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1084 "scanner.c" */
yy127:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy132;
			if (yych == 't') goto yy132;
			goto yy101;
yy128:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy129;
			if (yych != 'l') goto yy101;
yy129:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy130;
			if (yych != 'l') goto yy101;
yy130:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy131;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy131;
					if (yych <= 'z') goto yy100;
				}
			}
yy131:
/* #line 280 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1122 "scanner.c" */
yy132:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy133;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy133;
					if (yych <= 'z') goto yy100;
				}
			}
yy133:
/* #line 200 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1147 "scanner.c" */
yy134:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy143;
			if (yych == 'f') goto yy143;
			goto yy101;
yy135:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy137;
				if (yych <= 'L') goto yy101;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy101;
					goto yy137;
				} else {
					if (yych != 'm') goto yy101;
				}
			}
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy140;
			if (yych == 'i') goto yy140;
			goto yy101;
yy137:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy138;
			if (yych != 'e') goto yy101;
yy138:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy139;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy139;
					if (yych <= 'z') goto yy100;
				}
			}
yy139:
/* #line 215 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1198 "scanner.c" */
yy140:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy141;
			if (yych != 't') goto yy101;
yy141:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy142;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy142;
					if (yych <= 'z') goto yy100;
				}
			}
yy142:
/* #line 190 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 1227 "scanner.c" */
yy143:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy144;
			if (yych != 't') goto yy101;
yy144:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy145;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy145;
					if (yych <= 'z') goto yy100;
				}
			}
yy145:
/* #line 250 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1256 "scanner.c" */
yy146:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy147;
			if (yych != 'v') goto yy101;
yy147:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy148;
			if (yych != 'i') goto yy101;
yy148:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy149;
			if (yych != 'n') goto yy101;
yy149:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy150;
			if (yych != 'g') goto yy101;
yy150:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy151;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy151;
					if (yych <= 'z') goto yy100;
				}
			}
yy151:
/* #line 185 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 1297 "scanner.c" */
yy152:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy153;
			if (yych != 'o') goto yy101;
yy153:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy154;
			if (yych != 'u') goto yy101;
yy154:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy155;
			if (yych != 'p') goto yy101;
yy155:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy156;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy156;
					if (yych <= 'z') goto yy100;
				}
			}
yy156:
/* #line 180 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 1334 "scanner.c" */
yy157:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy171;
			if (yych == 'f') goto yy171;
			goto yy101;
yy158:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy159;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy159;
					if (yych <= 'z') goto yy100;
				}
			}
yy159:
/* #line 235 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1364 "scanner.c" */
yy160:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy161;
					if (yych <= ':') goto yy100;
				} else {
					if (yych == 'D') goto yy167;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy100;
					if (yych == '_') goto yy100;
				} else {
					if (yych == 'd') goto yy167;
					if (yych <= 'z') goto yy100;
				}
			}
yy161:
/* #line 210 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1390 "scanner.c" */
yy162:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy163;
			if (yych != 't') goto yy101;
yy163:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy164;
			if (yych != 'e') goto yy101;
yy164:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy165;
			if (yych != 'r') goto yy101;
yy165:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy166;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy166;
					if (yych <= 'z') goto yy100;
				}
			}
yy166:
/* #line 265 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 1427 "scanner.c" */
yy167:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy168;
			if (yych != 'e') goto yy101;
yy168:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy169;
			if (yych != 'r') goto yy101;
yy169:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy170;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy170;
					if (yych <= 'z') goto yy100;
				}
			}
yy170:
/* #line 160 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 1460 "scanner.c" */
yy171:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy172;
			if (yych != 's') goto yy101;
yy172:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy173;
			if (yych != 'e') goto yy101;
yy173:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy174;
			if (yych != 't') goto yy101;
yy174:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy175;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy175;
					if (yych <= 'z') goto yy100;
				}
			}
yy175:
/* #line 195 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 1497 "scanner.c" */
yy176:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy177;
			if (yych != 'e') goto yy101;
yy177:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'N') goto yy178;
				if (yych <= 'Q') goto yy101;
				goto yy180;
			} else {
				if (yych <= 'n') {
					if (yych <= 'm') goto yy101;
				} else {
					if (yych == 'r') goto yy180;
					goto yy101;
				}
			}
yy178:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy179;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy179;
					if (yych <= 'z') goto yy100;
				}
			}
yy179:
/* #line 340 "scanner.re" */
			{
			token->opcode = PHQL_T_WHEN;
			return 0;
		}
/* #line 1540 "scanner.c" */
yy180:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy181;
			if (yych != 'e') goto yy101;
yy181:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy182;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy182;
					if (yych <= 'z') goto yy100;
				}
			}
yy182:
/* #line 150 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 1569 "scanner.c" */
yy183:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy184;
			if (yych != 'l') goto yy101;
yy184:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy185;
			if (yych != 'u') goto yy101;
yy185:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy186;
			if (yych != 'e') goto yy101;
yy186:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy187;
			if (yych != 's') goto yy101;
yy187:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy188;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy188;
					if (yych <= 'z') goto yy100;
				}
			}
yy188:
/* #line 145 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 1610 "scanner.c" */
yy189:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy206;
			if (yych == 'i') goto yy206;
			goto yy101;
yy190:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'N') {
					if (yych <= ':') {
						if (yych >= '0') goto yy100;
					} else {
						if (yych <= '@') goto yy191;
						if (yych <= 'M') goto yy100;
						goto yy196;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'R') goto yy100;
						goto yy194;
					} else {
						if (yych <= 'T') goto yy195;
						if (yych <= 'Z') goto yy100;
					}
				}
			} else {
				if (yych <= 'm') {
					if (yych <= '^') {
						if (yych <= '\\') goto yy100;
					} else {
						if (yych != '`') goto yy100;
					}
				} else {
					if (yych <= 's') {
						if (yych <= 'n') goto yy196;
						if (yych <= 'r') goto yy100;
						goto yy194;
					} else {
						if (yych <= 't') goto yy195;
						if (yych <= 'z') goto yy100;
					}
				}
			}
yy191:
/* #line 230 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1660 "scanner.c" */
yy192:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy193;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy193;
					if (yych <= 'z') goto yy100;
				}
			}
yy193:
/* #line 275 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1685 "scanner.c" */
yy194:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy202;
			if (yych == 'e') goto yy202;
			goto yy101;
yy195:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy200;
			if (yych == 'o') goto yy200;
			goto yy101;
yy196:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy197;
			if (yych != 'e') goto yy101;
yy197:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy198;
			if (yych != 'r') goto yy101;
yy198:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy199;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy199;
					if (yych <= 'z') goto yy100;
				}
			}
yy199:
/* #line 245 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 1728 "scanner.c" */
yy200:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy201;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy201;
					if (yych <= 'z') goto yy100;
				}
			}
yy201:
/* #line 140 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 1753 "scanner.c" */
yy202:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy203;
			if (yych != 'r') goto yy101;
yy203:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy204;
			if (yych != 't') goto yy101;
yy204:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy205;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy205;
					if (yych <= 'z') goto yy100;
				}
			}
yy205:
/* #line 135 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 1786 "scanner.c" */
yy206:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy207;
			if (yych != 'k') goto yy101;
yy207:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy208;
			if (yych != 'e') goto yy101;
yy208:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy209;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy209;
					if (yych <= 'z') goto yy100;
				}
			}
yy209:
/* #line 220 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 1819 "scanner.c" */
yy210:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy213;
				if (yych <= 'S') goto yy101;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy101;
					goto yy213;
				} else {
					if (yych != 't') goto yy101;
				}
			}
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy212;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy212;
					if (yych <= 'z') goto yy100;
				}
			}
yy212:
/* #line 115 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 1856 "scanner.c" */
yy213:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy214;
			if (yych != 'e') goto yy101;
yy214:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy215;
			if (yych != 'c') goto yy101;
yy215:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy216;
			if (yych != 't') goto yy101;
yy216:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy217;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy217;
					if (yych <= 'z') goto yy100;
				}
			}
yy217:
/* #line 155 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 1893 "scanner.c" */
yy218:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy224;
			if (yych == 'd') goto yy224;
			goto yy101;
yy219:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy220;
			if (yych != 'i') goto yy101;
yy220:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy221;
			if (yych != 'n') goto yy101;
yy221:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy222;
			if (yych != 'g') goto yy101;
yy222:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy223;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy223;
					if (yych <= 'z') goto yy100;
				}
			}
yy223:
/* #line 310 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 1935 "scanner.c" */
yy224:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy225;
			if (yych != 'a') goto yy101;
yy225:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy226;
			if (yych != 't') goto yy101;
yy226:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy227;
			if (yych != 'e') goto yy101;
yy227:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy228;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy228;
					if (yych <= 'z') goto yy100;
				}
			}
yy228:
/* #line 110 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 1972 "scanner.c" */
yy229:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 32) {
				goto yy229;
			}
			if (yych != ':') goto yy97;
			++YYCURSOR;
/* #line 102 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1989 "scanner.c" */
yy233:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy233;
			}
/* #line 93 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2004 "scanner.c" */
yy236:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy238;
			if (yych <= '9') goto yy236;
yy238:
/* #line 84 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2019 "scanner.c" */
yy239:
			++YYCURSOR;
			yych = *YYCURSOR;
yy240:
			if (yybm[0+yych] & 128) {
				goto yy239;
			}
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '9') goto yy3;
					goto yy100;
				} else {
					if (yych <= 'F') goto yy3;
					if (yych <= 'Z') goto yy100;
					goto yy3;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych <= '^') goto yy3;
					goto yy100;
				} else {
					if (yych <= '`') goto yy3;
					if (yych <= 'z') goto yy100;
					goto yy3;
				}
			}
yy241:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy253;
			if (yych == 'l') goto yy253;
			goto yy240;
yy242:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy251;
			if (yych == 'r') goto yy251;
			goto yy101;
yy243:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy248;
			if (yych == 'o') goto yy248;
			goto yy101;
yy244:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy245;
			if (yych != 'l') goto yy101;
yy245:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy246;
			if (yych != 'l') goto yy101;
yy246:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy247;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy247;
					if (yych <= 'z') goto yy100;
				}
			}
yy247:
/* #line 270 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 2094 "scanner.c" */
yy248:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy249;
			if (yych != 'm') goto yy101;
yy249:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy250;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy250;
					if (yych <= 'z') goto yy100;
				}
			}
yy250:
/* #line 125 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 2123 "scanner.c" */
yy251:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy252;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy252;
					if (yych <= 'z') goto yy100;
				}
			}
yy252:
/* #line 330 "scanner.re" */
			{
			token->opcode = PHQL_T_FOR;
			return 0;
		}
/* #line 2148 "scanner.c" */
yy253:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy254;
			if (yych != 's') goto yy101;
yy254:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy255;
			if (yych != 'e') goto yy101;
yy255:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy256;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy256;
					if (yych <= 'z') goto yy100;
				}
			}
yy256:
/* #line 325 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 2181 "scanner.c" */
yy257:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy268;
			if (yych == 's') goto yy268;
			goto yy101;
yy258:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy266;
			if (yych == 'd') goto yy266;
			goto yy101;
yy259:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy261;
			if (yych == 'i') goto yy261;
			goto yy101;
yy260:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy261;
			if (yych != 'i') goto yy240;
yy261:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy262;
			if (yych != 's') goto yy101;
yy262:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy263;
			if (yych != 't') goto yy101;
yy263:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy264;
			if (yych != 's') goto yy101;
yy264:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy265;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy265;
					if (yych <= 'z') goto yy100;
				}
			}
yy265:
/* #line 315 "scanner.re" */
			{
			token->opcode = PHQL_T_EXISTS;
			return 0;
		}
/* #line 2237 "scanner.c" */
yy266:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy267;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy267;
					if (yych <= 'z') goto yy100;
				}
			}
yy267:
/* #line 355 "scanner.re" */
			{
			token->opcode = PHQL_T_END;
			return 0;
		}
/* #line 2262 "scanner.c" */
yy268:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy269;
			if (yych != 'e') goto yy101;
yy269:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy270;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy270;
					if (yych <= 'z') goto yy100;
				}
			}
yy270:
/* #line 350 "scanner.re" */
			{
			token->opcode = PHQL_T_ELSE;
			return 0;
		}
/* #line 2291 "scanner.c" */
yy271:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy280;
				if (yych <= 'R') goto yy240;
				goto yy281;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy240;
					goto yy280;
				} else {
					if (yych == 's') goto yy281;
					goto yy240;
				}
			}
yy272:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy273;
			if (yych != 's') goto yy101;
yy273:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy274;
			if (yych != 't') goto yy101;
yy274:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy275;
			if (yych != 'i') goto yy101;
yy275:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy276;
			if (yych != 'n') goto yy101;
yy276:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy277;
			if (yych != 'c') goto yy101;
yy277:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy278;
			if (yych != 't') goto yy101;
yy278:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy279;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy279;
					if (yych <= 'z') goto yy100;
				}
			}
yy279:
/* #line 285 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2355 "scanner.c" */
yy280:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy284;
			if (yych == 'e') goto yy284;
			goto yy101;
yy281:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy282;
			if (yych != 'c') goto yy101;
yy282:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy283;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy283;
					if (yych <= 'z') goto yy100;
				}
			}
yy283:
/* #line 175 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 2389 "scanner.c" */
yy284:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy285;
			if (yych != 't') goto yy101;
yy285:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy286;
			if (yych != 'e') goto yy101;
yy286:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy287;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy287;
					if (yych <= 'z') goto yy100;
				}
			}
yy287:
/* #line 120 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2422 "scanner.c" */
yy288:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy301;
			if (yych == 's') goto yy301;
			goto yy240;
yy289:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy295;
			if (yych == 'n') goto yy295;
			goto yy101;
yy290:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy291;
			if (yych != 'o') goto yy101;
yy291:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy292;
			if (yych != 's') goto yy101;
yy292:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy293;
			if (yych != 's') goto yy101;
yy293:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy294;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy294;
					if (yych <= 'z') goto yy100;
				}
			}
yy294:
/* #line 260 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 2469 "scanner.c" */
yy295:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy296;
			if (yych != 'v') goto yy101;
yy296:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy297;
			if (yych != 'e') goto yy101;
yy297:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy298;
			if (yych != 'r') goto yy101;
yy298:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy299;
			if (yych != 't') goto yy101;
yy299:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy300;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy300;
					if (yych <= 'z') goto yy100;
				}
			}
yy300:
/* #line 305 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 2510 "scanner.c" */
yy301:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'E') goto yy302;
				if (yych <= 'S') goto yy101;
				goto yy304;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy101;
				} else {
					if (yych == 't') goto yy304;
					goto yy101;
				}
			}
yy302:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy303;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy303;
					if (yych <= 'z') goto yy100;
				}
			}
yy303:
/* #line 335 "scanner.re" */
			{
			token->opcode = PHQL_T_CASE;
			return 0;
		}
/* #line 2549 "scanner.c" */
yy304:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy305;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy305;
					if (yych <= 'z') goto yy100;
				}
			}
yy305:
/* #line 300 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 2574 "scanner.c" */
yy306:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy309;
			if (yych == 't') goto yy309;
			goto yy240;
yy307:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy308;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy308;
					if (yych <= 'z') goto yy100;
				}
			}
yy308:
/* #line 165 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 2604 "scanner.c" */
yy309:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy310;
			if (yych != 'w') goto yy101;
yy310:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy311;
			if (yych != 'e') goto yy101;
yy311:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy312;
			if (yych != 'e') goto yy101;
yy312:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy313;
			if (yych != 'n') goto yy101;
yy313:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy314;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy314;
					if (yych <= 'z') goto yy100;
				}
			}
yy314:
/* #line 295 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 2645 "scanner.c" */
yy315:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy326;
			if (yych == 'a') goto yy326;
			goto yy101;
yy316:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy324;
			if (yych == 'l') goto yy324;
			goto yy101;
yy317:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy322;
			if (yych == 'd') goto yy322;
			goto yy101;
yy318:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy319;
					if (yych <= ':') goto yy100;
				} else {
					if (yych == 'C') goto yy320;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy100;
					if (yych == '_') goto yy100;
				} else {
					if (yych == 'c') goto yy320;
					if (yych <= 'z') goto yy100;
				}
			}
yy319:
/* #line 130 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 2686 "scanner.c" */
yy320:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy321;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy321;
					if (yych <= 'z') goto yy100;
				}
			}
yy321:
/* #line 170 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 2711 "scanner.c" */
yy322:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy323;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy323;
					if (yych <= 'z') goto yy100;
				}
			}
yy323:
/* #line 205 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 2736 "scanner.c" */
yy324:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy325;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy325;
					if (yych <= 'z') goto yy100;
				}
			}
yy325:
/* #line 290 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 2761 "scanner.c" */
yy326:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy327;
			if (yych != 'i') goto yy101;
yy327:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy328;
			if (yych != 'n') goto yy101;
yy328:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy329;
			if (yych != 's') goto yy101;
yy329:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy330;
			if (yych != 't') goto yy101;
yy330:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy331;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy331;
					if (yych <= 'z') goto yy100;
				}
			}
yy331:
/* #line 225 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 2802 "scanner.c" */
yy332:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy238;
			if (yych <= '9') goto yy332;
			goto yy238;
yy334:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '@') {
				if (yych <= '.') {
					if (yych <= '-') goto yy3;
					goto yy332;
				} else {
					if (yych <= '/') goto yy3;
					if (yych <= '9') goto yy334;
					goto yy3;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'F') goto yy336;
					if (yych <= '`') goto yy3;
				} else {
					if (yych != 'x') goto yy3;
				}
			}
yy336:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'F') {
				if (yych <= '/') goto yy3;
				if (yych <= '9') goto yy336;
				if (yych <= '@') goto yy3;
				goto yy336;
			} else {
				if (yych <= 'f') {
					if (yych <= '`') goto yy3;
					goto yy336;
				} else {
					if (yych == 'x') goto yy336;
					goto yy3;
				}
			}
yy338:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy339;
			if (yych == 'r') goto yy251;
			goto yy101;
yy339:
			yych = *++YYCURSOR;
			if (yych <= 'Z') {
				if (yych <= '@') {
					if (yych <= '/') goto yy252;
					if (yych <= ':') goto yy100;
					goto yy252;
				} else {
					if (yych != 'C') goto yy100;
				}
			} else {
				if (yych <= '^') {
					if (yych == '\\') goto yy100;
					goto yy252;
				} else {
					if (yych == '`') goto yy252;
					if (yych <= 'z') goto yy100;
					goto yy252;
				}
			}
yy340:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'Z') {
				if (yych <= '@') {
					if (yych <= '/') goto yy19;
					if (yych <= ':') goto yy100;
					goto yy19;
				} else {
					if (yych != 'E') goto yy100;
				}
			} else {
				if (yych <= '^') {
					if (yych == '\\') goto yy100;
					goto yy19;
				} else {
					if (yych == '`') goto yy19;
					if (yych <= 'z') goto yy100;
					goto yy19;
				}
			}
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'I') {
				if (yych <= '@') {
					if (yych <= '/') goto yy19;
					if (yych <= ':') goto yy100;
					goto yy19;
				} else {
					if (yych == 'F') goto yy342;
					if (yych <= 'H') goto yy100;
					goto yy343;
				}
			} else {
				if (yych <= '^') {
					if (yych == '[') goto yy19;
					if (yych <= '\\') goto yy100;
					goto yy19;
				} else {
					if (yych == '`') goto yy19;
					if (yych <= 'z') goto yy100;
					goto yy19;
				}
			}
yy342:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'Z') {
				if (yych <= '@') {
					if (yych <= '/') goto yy19;
					if (yych <= ':') goto yy100;
					goto yy19;
				} else {
					if (yych == 'O') goto yy349;
					goto yy100;
				}
			} else {
				if (yych <= '^') {
					if (yych == '\\') goto yy100;
					goto yy19;
				} else {
					if (yych == '`') goto yy19;
					if (yych <= 'z') goto yy100;
					goto yy19;
				}
			}
yy343:
			yych = *++YYCURSOR;
			if (yych != 'N') goto yy101;
			yych = *++YYCURSOR;
			if (yych != 'D') goto yy101;
			yych = *++YYCURSOR;
			if (yych != 'E') goto yy101;
			yych = *++YYCURSOR;
			if (yych != 'X') goto yy101;
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy348;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy348;
					if (yych <= 'z') goto yy100;
				}
			}
yy348:
/* #line 41 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 2972 "scanner.c" */
yy349:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'Z') {
				if (yych <= '@') {
					if (yych <= '/') goto yy19;
					if (yych <= ':') goto yy100;
					goto yy19;
				} else {
					if (yych != 'R') goto yy100;
				}
			} else {
				if (yych <= '^') {
					if (yych == '\\') goto yy100;
					goto yy19;
				} else {
					if (yych == '`') goto yy19;
					if (yych <= 'z') goto yy100;
					goto yy19;
				}
			}
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'Z') {
				if (yych <= '@') {
					if (yych <= '/') goto yy19;
					if (yych <= ':') goto yy100;
					goto yy19;
				} else {
					if (yych == 'C') goto yy340;
					goto yy100;
				}
			} else {
				if (yych <= '^') {
					if (yych == '\\') goto yy100;
					goto yy19;
				} else {
					if (yych == '`') goto yy19;
					if (yych <= 'z') goto yy100;
					goto yy19;
				}
			}
		}
/* #line 552 "scanner.re" */

	}

	return status;
}
